### ISSUE TITLE
Is it possible to boot from Internal SSD?

### ISSUE THREAD

**Issue by xswqaz** [AdityaGarg8/mbp-16.x-ubuntu-kernel#18]
After T2 patch, Is it possible to boot from Internal SSD?

**Comment by Redecorating** [comment]
It's possible on both normal linux kernels and T2 linux kernels.

To boot linux from the internal ssd you need to have secure boot turned off, and a kernel version greater than 5.4, which will include quirks for the T2 SSD controller. These quirks are already in upstream kernels, which is why it works with upstream kernels.

**Comment by xswqaz** [comment]
Thank you for reply. I'll try it

**Comment by xswqaz** [comment]
There was error to clean install ubuntu to mac mini 2018 (T2) 
unable to install grub-install /dev/nvme0n1 failed

Any workaround?

**Comment by AdityaGarg8** [comment]
You are using an official Ubuntu ISO, which won't work.
Try using https://github.com/AdityaGarg8/mbp-ubuntu/releases/tag/v20.04-5.17.1

**Comment by xswqaz** [comment]
I can execute grub-install with official 22.04 iso 

sudo -s
mount /dev/nvme0n1p2 /mnt
mount /dev/nvme0n1p1 /mnt/boot/efi
for i in /dev /dev/pts /proc /sys /run; do sudo mount -B $i /mnt$i; done
sudo chroot /mnt
grub-install --force /dev/nvme0n1
update-grub
