### ISSUE TITLE
linux-headers-6.2.5-t2-kinetic is not supported...

### ISSUE THREAD

**Issue by moon47usaco** [AdityaGarg8/mbp-16.x-ubuntu-kernel#36]
ERROR (dkms apport): kernel package linux-headers-6.2.5-t2-kinetic is not supported

I get this all the time. I have everything set up from https://wiki.t2linux.org/guides/postinstall/ and working properly however, I do not seem to have utilization of the AMD gpu.

I have tried several ways to get ROCm working but I always run into this before being able to complete.

Tried both on AMD offical docs and from this repo https://github.com/novaspirit/amdgpu-rocm-ubu22.

Using the repo I can not install the prerequisite: libstdc++-10-dev

**Comment by AdityaGarg8** [comment]
AMD GPU Pro iirc supports kernel 5.15, so you'll have to download a 5.15 kernel.

You can manually install that from the releases, although we have stop supporting that kernel version since 6.2 has been released, so you won't get kernel updates from us for 5.15 LTS.

Although, tbh I've never succeed getting AMD GPU Pro to work, since I get some error every time, but the error you are facing, is probably due to the kernel.

**Comment by AdityaGarg8** [comment]
closing due to no response from user.
